CREATE DATABASE REGISTRO_VACINA_COVID19;
USE REGISTRO_VACINA_COVID19;
 
  CREATE TABLE PESSOA (
  idPESSOA INT NOT NULL AUTO_INCREMENT
  , Nome VARCHAR(100) NOT NULL
  , DataNascimento DATE NOT NULL
  , Sexo CHAR(1) NOT NULL
  , CPF CHAR(11) NOT NULL
 , PRIMARY KEY (idPESSOA)
);

CREATE TABLE PESQUISADORES (
  idPESQUISADORES INT NOT NULL AUTO_INCREMENT
  , InstituicaoAssociada VARCHAR(100) NOT NULL
  , PESSOA_idPESSOA INT NOT NULL
  , PRIMARY KEY (idPESQUISADORES)
  , CONSTRAINT idPESSOA
  , FOREIGN KEY (PESSOA_idPESSOA)
    REFERENCES PESSOA (idPESSOA)
);   

CREATE TABLE PUBLICO (
  idPUBLICO INT NOT NULL AUTO_INCREMENT
  , Voluntario CHAR(1) NOT NULL
  , PESSOA_idPESSOA INT NOT NULL
  , PRIMARY KEY (idPUBLICO)
  , CONSTRAINT idPESSOA
  ,  FOREIGN KEY (PESSOA_idPESSOA)
    REFERENCES PESSOA (idPESSOA)
);

CREATE TABLE VACINA (
  idVACINA INT NOT NULL AUTO_INCREMENT
  , PaisOrigem VARCHAR(100) NOT NULL
  , EstagioPesquisa CHAR(1) NOT NULL
  , DataInicioPesquisa DATE NOT NULL
  , PESQUISADORES_idPESQUISADORES INT NOT NULL
  , PRIMARY KEY (idVACINA)
  , CONSTRAINT idPESQUISADORES
  ,  FOREIGN KEY (PESQUISADORES_idPESQUISADORES)
    REFERENCES PESQUISADORES (idPESQUISADORES)
  );

CREATE TABLE APLICACAO_VACINA (
  idAPLICACAO_VACINA INT NOT NULL AUTO_INCREMENT
  , DataAplicacao DATE NOT NULL
  , Avaliacao CHAR(1) NOT NULL
  , VACINA_idVACINA INT NOT NULL
  , PESSOA_idPESSOA INT NOT NULL
  , PRIMARY KEY (idAPLICACAO_VACINA)
  , CONSTRAINT idVACINA
  ,  FOREIGN KEY (VACINA_idVACINA)
    REFERENCES VACINA (idVACINA)
   , CONSTRAINT idPESSOA
   , FOREIGN KEY (PESSOA_idPESSOA)
    REFERENCES PESSOA (idPESSOA)
);

